# Generated by Django 4.1 on 2022-08-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField()),
                ('cantidad_hijos', models.IntegerField(default=0)),
                ('tiene_mascotas', models.BooleanField()),
            ],
        ),
    ]
